version: '3.4'

services:
  cosmonautics-front:
    image: cosmonautics-front
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js